version: '3.4'
name: docker-finalcase-creditwisehub-compose
services:
 postgres:
  container_name: container-pg
  image: postgres
  hostname: localhost
  ports:
  - "5432:5432"
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: root
   POSTGRES_DB: "HangfireDB"
  volumes:
  - postgres-data:/var/lib/postgresql/data
  - "./scripts/init.sql:/docker-entrypoint-initdb.d/script.sql"
  restart: unless-stopped

 creditwisehub.api:
  container_name: creditwise-hub
  image: ${DOCKER_REGISTRY-}creditwisehubapi
  build:
    context: .
    dockerfile: CreditWiseHub.API/Dockerfile
  depends_on:
  - postgres


 pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
  

