--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1

-- Started on 2024-01-07 12:27:48 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE DATABASE "CreditWiseHubDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "CreditWiseHubDB" OWNER TO admin;

\connect "CreditWiseHubDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16736)
-- Name: AccountTypes; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AccountTypes" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "MinimumOpeningBalance" numeric(18,2) NOT NULL,
    "Description" character varying(255),
    "CreatedDate" timestamp with time zone DEFAULT '2024-01-07 09:50:44.219246+00'::timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "IsActive" boolean DEFAULT true NOT NULL
);


ALTER TABLE public."AccountTypes" OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 16735)
-- Name: AccountTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AccountTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AccountTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16799)
-- Name: Accounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Accounts" (
    "Id" uuid NOT NULL,
    "AccountNumber" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Balance" numeric NOT NULL,
    "UserAppId" text NOT NULL,
    "AccountTypeId" integer NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '2024-01-07 09:50:44.219011+00'::timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "IsActive" boolean DEFAULT true NOT NULL
);


ALTER TABLE public."Accounts" OWNER TO admin;

--
-- TOC entry 239 (class 1259 OID 16898)
-- Name: AffectedAccounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AffectedAccounts" (
    "Id" bigint NOT NULL,
    "AccountNumber" text NOT NULL,
    "Description" character varying(255),
    "IsReceiverAccount" boolean NOT NULL,
    "IsExternal" boolean,
    "BeforeBalance" numeric(18,2),
    "AfterBalance" numeric(18,2),
    "TransactionId" bigint NOT NULL
);


ALTER TABLE public."AffectedAccounts" OWNER TO admin;

--
-- TOC entry 238 (class 1259 OID 16897)
-- Name: AffectedAccounts_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AffectedAccounts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AffectedAccounts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16787)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO admin;

--
-- TOC entry 227 (class 1259 OID 16786)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16743)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO admin;

--
-- TOC entry 231 (class 1259 OID 16819)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO admin;

--
-- TOC entry 230 (class 1259 OID 16818)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16831)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO admin;

--
-- TOC entry 233 (class 1259 OID 16843)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO admin;

--
-- TOC entry 234 (class 1259 OID 16860)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 16750)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Surname" character varying(50) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT '2024-01-07 09:50:44.220815+00'::timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO admin;

--
-- TOC entry 243 (class 1259 OID 16934)
-- Name: AutomaticPaymentHistories; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AutomaticPaymentHistories" (
    "Id" bigint NOT NULL,
    "RegistrationId" bigint NOT NULL,
    "Comment" text NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "PaymentAmount" numeric NOT NULL,
    "IsPaid" boolean NOT NULL,
    "TransactionId" bigint
);


ALTER TABLE public."AutomaticPaymentHistories" OWNER TO admin;

--
-- TOC entry 242 (class 1259 OID 16933)
-- Name: AutomaticPaymentHistories_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AutomaticPaymentHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AutomaticPaymentHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16873)
-- Name: AutomaticPaymentRegistrations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AutomaticPaymentRegistrations" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "PaymentType" integer NOT NULL,
    "PaymentAmount" numeric(18,2) NOT NULL,
    "PaymentDueDay" integer NOT NULL,
    "PaymentDueCount" integer NOT NULL,
    "PaymentDuePaidCount" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "UserId" text NOT NULL,
    "BelongToSystem" boolean NOT NULL
);


ALTER TABLE public."AutomaticPaymentRegistrations" OWNER TO admin;

--
-- TOC entry 235 (class 1259 OID 16872)
-- Name: AutomaticPaymentRegistrations_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AutomaticPaymentRegistrations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AutomaticPaymentRegistrations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16760)
-- Name: ExternalAccountInformations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."ExternalAccountInformations" (
    "Id" bigint NOT NULL,
    "AccountNumber" text NOT NULL,
    "BankName" text NOT NULL,
    "OwnerFullName" text NOT NULL
);


ALTER TABLE public."ExternalAccountInformations" OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 16759)
-- Name: ExternalAccountInformations_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."ExternalAccountInformations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExternalAccountInformations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16911)
-- Name: LoanApplications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."LoanApplications" (
    "Id" bigint NOT NULL,
    "UserId" text NOT NULL,
    "LoanTypeId" integer NOT NULL,
    "RequestedAmount" numeric(18,2) NOT NULL,
    "InstallmentCount" integer NOT NULL,
    "IsRejected" boolean,
    "IsApproved" boolean NOT NULL,
    "ApproverId" text,
    "ApprovalDate" timestamp with time zone,
    "TransactionId" bigint,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."LoanApplications" OWNER TO admin;

--
-- TOC entry 240 (class 1259 OID 16910)
-- Name: LoanApplications_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."LoanApplications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LoanApplications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16768)
-- Name: LoanTypes; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."LoanTypes" (
    "Id" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "InterestRate" numeric(18,2) NOT NULL,
    "MaxInstallmentOption" integer NOT NULL,
    "MinInstallmentOption" integer NOT NULL,
    "MinLoanAmount" numeric(18,2) NOT NULL,
    "MaxLoanAmount" numeric(18,2) NOT NULL,
    "MinCreditScore" integer NOT NULL,
    "MaxCreditScore" integer NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."LoanTypes" OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 16767)
-- Name: LoanTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."LoanTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LoanTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16975)
-- Name: Tickets; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Tickets" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "ResolvedDate" timestamp with time zone,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "UserAppId" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Tickets" OWNER TO admin;

--
-- TOC entry 244 (class 1259 OID 16974)
-- Name: Tickets_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Tickets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tickets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16774)
-- Name: Transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Transactions" (
    "Id" bigint NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "IsConfirmed" boolean NOT NULL
);


ALTER TABLE public."Transactions" OWNER TO admin;

--
-- TOC entry 224 (class 1259 OID 16773)
-- Name: Transactions_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Transactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16779)
-- Name: UserRefreshTokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."UserRefreshTokens" (
    "UserId" text NOT NULL,
    "Code" character varying(200) NOT NULL,
    "Expiration" timestamp with time zone NOT NULL
);


ALTER TABLE public."UserRefreshTokens" OWNER TO admin;

--
-- TOC entry 237 (class 1259 OID 16885)
-- Name: UserTransactionLimits; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."UserTransactionLimits" (
    "UserId" text NOT NULL,
    "DailyTransactionLimit" numeric(18,2) NOT NULL,
    "DailyTransactionAmount" numeric(18,2) NOT NULL,
    "LastProcessDate" timestamp with time zone NOT NULL,
    "InstantTransactionLimit" numeric(18,2) NOT NULL
);


ALTER TABLE public."UserTransactionLimits" OWNER TO admin;

--
-- TOC entry 215 (class 1259 OID 16730)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- TOC entry 3298 (class 2606 OID 16742)
-- Name: AccountTypes PK_AccountTypes; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AccountTypes"
    ADD CONSTRAINT "PK_AccountTypes" PRIMARY KEY ("Id");


--
-- TOC entry 3320 (class 2606 OID 16807)
-- Name: Accounts PK_Accounts; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id");


--
-- TOC entry 3339 (class 2606 OID 16904)
-- Name: AffectedAccounts PK_AffectedAccounts; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AffectedAccounts"
    ADD CONSTRAINT "PK_AffectedAccounts" PRIMARY KEY ("Id");


--
-- TOC entry 3316 (class 2606 OID 16793)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3300 (class 2606 OID 16749)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3323 (class 2606 OID 16825)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3326 (class 2606 OID 16837)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3329 (class 2606 OID 16849)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3331 (class 2606 OID 16866)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3304 (class 2606 OID 16758)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3348 (class 2606 OID 16940)
-- Name: AutomaticPaymentHistories PK_AutomaticPaymentHistories; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AutomaticPaymentHistories"
    ADD CONSTRAINT "PK_AutomaticPaymentHistories" PRIMARY KEY ("Id");


--
-- TOC entry 3334 (class 2606 OID 16879)
-- Name: AutomaticPaymentRegistrations PK_AutomaticPaymentRegistrations; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AutomaticPaymentRegistrations"
    ADD CONSTRAINT "PK_AutomaticPaymentRegistrations" PRIMARY KEY ("Id");


--
-- TOC entry 3307 (class 2606 OID 16766)
-- Name: ExternalAccountInformations PK_ExternalAccountInformations; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."ExternalAccountInformations"
    ADD CONSTRAINT "PK_ExternalAccountInformations" PRIMARY KEY ("Id");


--
-- TOC entry 3344 (class 2606 OID 16917)
-- Name: LoanApplications PK_LoanApplications; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."LoanApplications"
    ADD CONSTRAINT "PK_LoanApplications" PRIMARY KEY ("Id");


--
-- TOC entry 3309 (class 2606 OID 16772)
-- Name: LoanTypes PK_LoanTypes; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."LoanTypes"
    ADD CONSTRAINT "PK_LoanTypes" PRIMARY KEY ("Id");


--
-- TOC entry 3351 (class 2606 OID 16981)
-- Name: Tickets PK_Tickets; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");


--
-- TOC entry 3311 (class 2606 OID 16778)
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id");


--
-- TOC entry 3313 (class 2606 OID 16785)
-- Name: UserRefreshTokens PK_UserRefreshTokens; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserRefreshTokens"
    ADD CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("UserId");


--
-- TOC entry 3336 (class 2606 OID 16891)
-- Name: UserTransactionLimits PK_UserTransactionLimits; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserTransactionLimits"
    ADD CONSTRAINT "PK_UserTransactionLimits" PRIMARY KEY ("UserId");


--
-- TOC entry 3296 (class 2606 OID 16734)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3302 (class 1259 OID 16959)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3317 (class 1259 OID 16951)
-- Name: IX_Accounts_AccountTypeId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Accounts_AccountTypeId" ON public."Accounts" USING btree ("AccountTypeId");


--
-- TOC entry 3318 (class 1259 OID 16952)
-- Name: IX_Accounts_UserAppId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Accounts_UserAppId" ON public."Accounts" USING btree ("UserAppId");


--
-- TOC entry 3337 (class 1259 OID 16953)
-- Name: IX_AffectedAccounts_TransactionId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AffectedAccounts_TransactionId" ON public."AffectedAccounts" USING btree ("TransactionId");


--
-- TOC entry 3314 (class 1259 OID 16954)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3321 (class 1259 OID 16956)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3324 (class 1259 OID 16957)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3327 (class 1259 OID 16958)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3345 (class 1259 OID 16961)
-- Name: IX_AutomaticPaymentHistories_RegistrationId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AutomaticPaymentHistories_RegistrationId" ON public."AutomaticPaymentHistories" USING btree ("RegistrationId");


--
-- TOC entry 3346 (class 1259 OID 16962)
-- Name: IX_AutomaticPaymentHistories_TransactionId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AutomaticPaymentHistories_TransactionId" ON public."AutomaticPaymentHistories" USING btree ("TransactionId");


--
-- TOC entry 3332 (class 1259 OID 16963)
-- Name: IX_AutomaticPaymentRegistrations_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AutomaticPaymentRegistrations_UserId" ON public."AutomaticPaymentRegistrations" USING btree ("UserId");


--
-- TOC entry 3340 (class 1259 OID 16964)
-- Name: IX_LoanApplications_LoanTypeId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_LoanApplications_LoanTypeId" ON public."LoanApplications" USING btree ("LoanTypeId");


--
-- TOC entry 3341 (class 1259 OID 16965)
-- Name: IX_LoanApplications_TransactionId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_LoanApplications_TransactionId" ON public."LoanApplications" USING btree ("TransactionId");


--
-- TOC entry 3342 (class 1259 OID 16966)
-- Name: IX_LoanApplications_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_LoanApplications_UserId" ON public."LoanApplications" USING btree ("UserId");


--
-- TOC entry 3349 (class 1259 OID 16987)
-- Name: IX_Tickets_UserAppId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_Tickets_UserAppId" ON public."Tickets" USING btree ("UserAppId");


--
-- TOC entry 3301 (class 1259 OID 16955)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3305 (class 1259 OID 16960)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3353 (class 2606 OID 16808)
-- Name: Accounts FK_Accounts_AccountTypes_AccountTypeId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "FK_Accounts_AccountTypes_AccountTypeId" FOREIGN KEY ("AccountTypeId") REFERENCES public."AccountTypes"("Id");


--
-- TOC entry 3354 (class 2606 OID 16813)
-- Name: Accounts FK_Accounts_AspNetUsers_UserAppId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Accounts"
    ADD CONSTRAINT "FK_Accounts_AspNetUsers_UserAppId" FOREIGN KEY ("UserAppId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3362 (class 2606 OID 16905)
-- Name: AffectedAccounts FK_AffectedAccounts_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AffectedAccounts"
    ADD CONSTRAINT "FK_AffectedAccounts_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES public."Transactions"("Id") ON DELETE CASCADE;


--
-- TOC entry 3352 (class 2606 OID 16794)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3355 (class 2606 OID 16826)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3356 (class 2606 OID 16838)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3357 (class 2606 OID 16850)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3358 (class 2606 OID 16855)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3359 (class 2606 OID 16867)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3366 (class 2606 OID 16941)
-- Name: AutomaticPaymentHistories FK_AutomaticPaymentHistories_AutomaticPaymentRegistrations_Reg~; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AutomaticPaymentHistories"
    ADD CONSTRAINT "FK_AutomaticPaymentHistories_AutomaticPaymentRegistrations_Reg~" FOREIGN KEY ("RegistrationId") REFERENCES public."AutomaticPaymentRegistrations"("Id") ON DELETE CASCADE;


--
-- TOC entry 3367 (class 2606 OID 16946)
-- Name: AutomaticPaymentHistories FK_AutomaticPaymentHistories_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AutomaticPaymentHistories"
    ADD CONSTRAINT "FK_AutomaticPaymentHistories_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES public."Transactions"("Id");


--
-- TOC entry 3360 (class 2606 OID 16880)
-- Name: AutomaticPaymentRegistrations FK_AutomaticPaymentRegistrations_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AutomaticPaymentRegistrations"
    ADD CONSTRAINT "FK_AutomaticPaymentRegistrations_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3363 (class 2606 OID 16918)
-- Name: LoanApplications FK_LoanApplications_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."LoanApplications"
    ADD CONSTRAINT "FK_LoanApplications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3364 (class 2606 OID 16923)
-- Name: LoanApplications FK_LoanApplications_LoanTypes_LoanTypeId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."LoanApplications"
    ADD CONSTRAINT "FK_LoanApplications_LoanTypes_LoanTypeId" FOREIGN KEY ("LoanTypeId") REFERENCES public."LoanTypes"("Id");


--
-- TOC entry 3365 (class 2606 OID 16928)
-- Name: LoanApplications FK_LoanApplications_Transactions_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."LoanApplications"
    ADD CONSTRAINT "FK_LoanApplications_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES public."Transactions"("Id") ON DELETE SET NULL;


--
-- TOC entry 3368 (class 2606 OID 16982)
-- Name: Tickets FK_Tickets_AspNetUsers_UserAppId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_AspNetUsers_UserAppId" FOREIGN KEY ("UserAppId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3361 (class 2606 OID 16892)
-- Name: UserTransactionLimits FK_UserTransactionLimits_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."UserTransactionLimits"
    ADD CONSTRAINT "FK_UserTransactionLimits_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- Completed on 2024-01-07 12:27:48 UTC

--
-- PostgreSQL database dump complete
--

